# Generated by Django 5.1.6 on 2025-03-05 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='barcode_image',
            field=models.ImageField(blank=True, null=True, upload_to='barcodes/'),
        ),
    ]
